name: my First Workflow
on: push
jobs:
    first_jub:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List and Read file
              run: |
                echo "my first github actions job"
                ls -ltra
                cat README.md

            - name: Gnerate ASCII Artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON ....RAWR" >> dragon.txt

            # - name: List files
            #   run: ls

            # - name: Read file
            #   run: cat README.md
